name: wallet
description: Crypto wallet package for Bitcoin, Ethereum and Tron written in pure Dart.
version: 0.0.13
repository: https://github.com/xclud/dart_wallet
homepage: https://github.com/xclud/dart_wallet

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  eip55: ^1.0.2
  pointycastle: ^3.7.3
  sec: ^1.1.0

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.22.0
